Memory refactoring
floofi-org/vixen pull request #4
Opened 2024-12-13 17:03 UTC by starscouts

This basically updates the code to match the currently documented architecture.

2024-12-13 19:02 UTC, ryze312 requested changes

2024-12-13 20:54 UTC, starscouts commented on arch/src/cpu/decoder.rs
> +        let instruction = u32::from_le_bytes([
Perhaps, will try later

2024-12-14 11:40 UTC, ryze312 requested changes

2024-12-14 11:40 UTC, ryze312 commented on arch/src/core/instruction.rs
> +        disassembled.push_str(&Operation::disassemble(value.operation as u16));
```suggestion
        let mut disassembled = Self::new();
        let operation = Operation::disassemble(value.operation as u16);
        disassembled.push_str(&operation);
```

2024-12-14 11:40 UTC, ryze312 commented on arch/src/core/instruction.rs
> +        }
Use `.ok().filter()` and don't inline operand

```suggestion
        for (i, (operand, mode)) in operands_with_modes.iter().enumerate() {
            #[allow(clippy::cast_possible_truncation)]
            let mode = Addressing::try_from(*mode as u8)
                .ok()
                .filter(|m| m != Addressing::Implied);

            if let Some(mode) = mode {
                if i > 0 {
                    disassembled.push_str(", ");
                }
                
                let operand = Operand::disassemble(*operand, value.cpu, mode);
                disassembled.push_str(&operand);         
            } else {
                disassembled.push_str("<unk>");
            }
        }
```

2024-12-14 11:42 UTC, ryze312 commented
Tried to do the second thing with an iterator, but it ended up a bit too funky, because [intersperse](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.intersperse) is unstable.

2024-12-14 12:00 UTC, ryze312 approved these changes
Goodie!

2024-12-14 12:02 UTC, merged